### ISSUE TITLE
filter falsely blocks video playbacks on video.Varzesh3.com

### ISSUE THREAD

**Issue by DrKalan** [farrokhi/adblock-iran#24]
The blocker filter also blocks all the video playbacks in the domain https://video.varzesh3.com

One example:

https://video.varzesh3.com/video/188726/%DA%AF%D9%84-%D8%A7%D9%88%D9%84-%D9%84%DB%8C%D9%88%D8%B1-%D9%BE%D9%88%D9%84-%D8%A8%D9%87-%D8%AA%D8%A7%D8%AA%D9%86%D9%87%D8%A7%D9%85(%D9%81%DB%8C%D8%B1%D9%85%DB%8C%D9%86%D9%88)

Thank you for the great job! keep it up!

**Comment by DRSDavidSoft** [comment]
@DrKalan This is not an issue with this list. It's because of [EasyPrivacy](https://easylist.to/easylist/easyprivacy.txt), specifically the **`.com/clk?`** rule. See this:
![clk_issue](https://user-images.githubusercontent.com/4673812/64442563-4417a800-d0e5-11e9-813d-8ca89e36a09f.png)

@farrokhi You can close this issue, since it's not related to this project
